# application.yml
spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://admin:baobab123@mongodb:27017/baobab_academy?authSource=admin}
      # Configuration supplémentaire pour Docker
      auto-index-creation: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080

app:
  jwt:
    secret: ${JWT_SECRET:baobabAcademySecretKeyForJWTTokenGenerationMustBe32CharactersLong2024}
    expiration: 86400000 # 24 heures

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:3001}

file:
  upload-dir: ${FILE_UPLOAD_DIR:/app/uploads}

logging:
  level:
    com.example.baobab_academy: DEBUG
    org.springframework.data.mongodb: INFO
    org.springframework.security: INFO
    org.mongodb.driver: INFO
  file:
    name: /app/logs/baobab-academy.log

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Configuration MongoDB spécifique
mongodb:
  connection-timeout: 30000
  socket-timeout: 30000
  max-wait-time: 30000